services:
  - type: web
    name: ttd-backend
    env: python
    plan: free
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_backend:app --host 0.0.0.0 --port $PORT
